import test from 'node:test';
import assert from 'node:assert/strict';
import { ENVIRONMENT_DECLARATION_PROTOCOL, EnvironmentDeclarationRegistry } from '../src/runtime/environment-declaration.js';
import { ENVIRONMENT_LIFECYCLE_STAGES, EnvironmentLifecycleJournal } from '../src/runtime/environment-lifecycle-journal.js';
import { ENVIRONMENT_OBSERVATION_PROTOCOL } from '../src/runtime/environment-observation.js';
import { EnvironmentCreate } from '../src/runtime/environment-create.js';

function declaration() { return { protocol: ENVIRONMENT_DECLARATION_PROTOCOL, profile: 'linux-development', schemaGeneration: 'profile-v1', guest: { family: 'ubuntu', generation: '24.04.4' }, image: { identity: 'image-ubuntu-v1', generation: 'ubuntu-v1' }, resources: { memoryBytes: 4294967296, processorCount: 4 }, boot: { requirement: 'efi-v1' }, network: { requirement: 'managed-egress-v1' }, bootstrap: { generation: 'tooling-v1', requirements: ['runtime-js'] }, enrollment: { requirement: 'unique-guest-trust-v1' }, workspaces: [], protectedStateClasses: [] }; }
function memoryPort() { const values = new Map(); return { async load(key) { return structuredClone(values.get(key) ?? null); }, async save(key, value) { values.set(key, structuredClone(value)); }, async scan() { return [...values.values()].map((value) => structuredClone(value)); } }; }
function declarationPort() { const values = new Map(); return { async load(key) { return structuredClone(values.get(key) ?? null); }, async save(key, value) { values.set(key, structuredClone(value)); }, async scan() { return [...values.values()].map((value) => structuredClone(value)); } }; }
function observation(record, state, generation = null) { if (state === 'none') return { protocol: ENVIRONMENT_OBSERVATION_PROTOCOL, environmentIdentity: record.identity, declarationRevision: record.revision, implementationGeneration: null, materialization: 'none', systemStorage: 'unknown', attachment: 'unknown', enrollment: 'unknown', bootstrap: 'unknown', guest: 'unknown', transition: 'clear' }; return { protocol: ENVIRONMENT_OBSERVATION_PROTOCOL, environmentIdentity: record.identity, declarationRevision: record.revision, implementationGeneration: generation, materialization: 'present', systemStorage: 'present', attachment: 'ready', enrollment: 'ready', bootstrap: 'ready', guest: 'healthy', transition: 'clear' }; }
async function fixture() { const declarations = new EnvironmentDeclarationRegistry({ port: declarationPort(), now: () => '2026-08-22T08:30:00.000Z' }); const registered = await declarations.register(declaration()); const journal = new EnvironmentLifecycleJournal({ port: memoryPort(), now: () => '2026-08-22T08:30:01.000Z', id: () => 'lifecycle-create-1' }); return { declarations, registered: registered.record, journal }; }

test('create refuses to overwrite an observed materialization', async () => { const f = await fixture(); const create = new EnvironmentCreate({ declarations: f.declarations, journal: f.journal, observer: { observe: async () => observation(f.registered, 'present', 'implementation-1') }, fence: { acquire: async () => ({ subject: 'fence-1', release: async () => {} }) }, construction: { run: async () => ({}), clear: async () => {} } }); await assert.rejects(() => create.create(f.registered.identity), /refuses to overwrite/u); });

test('create journals the full lifecycle and keeps provider work behind one fence', async () => { const f = await fixture(); let state = 'none'; let fenceHeld = false; let released = 0; const create = new EnvironmentCreate({ declarations: f.declarations, journal: f.journal, observer: { observe: async () => observation(f.registered, state, state === 'none' ? null : 'implementation-1') }, fence: { acquire: async () => { fenceHeld = true; return { subject: 'fence-1', release: async () => { fenceHeld = false; released += 1; } }; } }, construction: { run: async () => { assert.equal(fenceHeld, true); state = 'present'; return { implementationGeneration: 'implementation-1' }; }, clear: async () => { assert.equal(fenceHeld, true); } } }); const result = await create.create(f.registered.identity); assert.equal(result.state, 'complete'); assert.equal(released, 1); const record = await f.journal.current(f.registered.identity); assert.deepEqual(record.entries.map((entry) => entry.stage), ENVIRONMENT_LIFECYCLE_STAGES); });

test('create resumes a failed construction with the same logical fence subject', async () => { const f = await fixture(); let state = 'none'; let first = true; let acquisitions = 0; const construction = { run: async () => { if (first) { first = false; throw new Error('interrupted'); } state = 'present'; return { implementationGeneration: 'implementation-1' }; }, clear: async () => {} }; const fence = { acquire: async () => { acquisitions += 1; return { subject: 'fence-stable', release: async () => {} }; } }; const create = new EnvironmentCreate({ declarations: f.declarations, journal: f.journal, observer: { observe: async () => observation(f.registered, state, state === 'none' ? null : 'implementation-1') }, fence, construction }); await assert.rejects(() => create.create(f.registered.identity), /interrupted/u); const active = await f.journal.current(f.registered.identity); assert.equal(active.entries.at(-1).stage, 'fenced-attempt'); const result = await create.create(f.registered.identity); assert.equal(result.state, 'complete'); assert.equal(acquisitions, 2); });
