import test from 'node:test';
import assert from 'node:assert/strict';
import { copyFile, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import { buildImageArtifactBundle } from '../src/runtime/image-artifact-bundle.js';
import { imageArtifactManifestDigest } from '../src/runtime/image-artifact-manifest.js';
import { ImageArtifactAcquisition } from '../src/runtime/image-artifact-acquisition.js';

function digest(value) { return createHash('sha256').update(value).digest('hex'); }
async function tempRoot() { return mkdtemp(path.join(os.tmpdir(), 'db-image-acquire-')); }
const codec = { algorithm: 'test-frame', async describe() { return { algorithm: 'test-frame', parameters: { version: '1' } }; }, async encode({ source, destination }) { await writeFile(destination, Buffer.concat([Buffer.from('F:'), await readFile(source)])); }, async decode({ source, destination, algorithm }) { if (algorithm !== 'test-frame') throw new Error('algorithm'); const bytes = await readFile(source); if (!bytes.subarray(0, 2).equals(Buffer.from('F:'))) throw new Error('frame'); await writeFile(destination, bytes.subarray(2)); } };
async function fixture(parent, { chunkBytes = 5 } = {}) { const canonical = path.join(parent, 'canonical.vhdx'); const bundle = path.join(parent, 'bundle'); await writeFile(canonical, Buffer.from('canonical-image-bytes-for-recovery')); const built = await buildImageArtifactBundle({ canonical, destination: bundle, profile: 'linux-development', generation: 'ubuntu-v1', format: 'vhdx', virtualSize: 8192, bootstrap: 'tooling-v1', codec, chunkBytes }); return { canonical, bundle, ...built }; }
function sourceFor(fixture, hooks = {}) { let manifestCalls = 0; const fetches = []; return { calls: () => ({ manifestCalls, fetches: [...fetches] }), async manifest() { manifestCalls += 1; const manifest = hooks.manifest ? hooks.manifest(structuredClone(fixture.manifest)) : fixture.manifest; return { manifest, digest: hooks.manifestDigest ?? imageArtifactManifestDigest(manifest) }; }, async fetch({ name, destination, size }) { fetches.push(name); if (hooks.failFetch?.(name, fetches.length)) throw new Error('injected fetch failure'); const bytes = Buffer.from(await readFile(path.join(fixture.bundle, name))); const output = hooks.chunk?.(name, bytes) ?? bytes; if (size != null && hooks.assertSize) hooks.assertSize(size, bytes.length); await writeFile(destination, output); } }; }
function fixtureIdentity(profile, generation, sha) { return `img-${createHash('sha256').update(`${profile}\0${generation}\0${sha}`).digest('hex').slice(0, 32)}`; }
function localPort(parent, options = {}) { const objects = new Map(); const quarantined = []; const cache = path.join(parent, 'local'); return { objects, quarantined, async verify(identity) { if (options.before && !objects.has(identity)) return options.before(identity); const entry = objects.get(identity); if (!entry) return { exists: false, usable: false, verified: false, entry: null }; const bytes = await readFile(entry.location); const valid = digest(bytes) === entry.digest; return { exists: true, usable: valid, verified: valid, entry: { generation: entry.generation }, location: entry.location }; }, async quarantine(identity) { quarantined.push(identity); objects.delete(identity); }, async publish(input, { validate } = {}) { await mkdir(cache, { recursive: true }); if (validate) await validate({ location: input.source, digest: input.expectedDigest, size: (await readFile(input.source)).length }); const location = path.join(cache, `${input.profile}-${input.generation}.img`); await copyFile(input.source, location); const bytes = await readFile(location); const identity = fixtureIdentity(input.profile, input.generation, digest(bytes)); objects.set(identity, { location, digest: digest(bytes), generation: input.generation }); return { identity, generation: input.generation }; } }; }

test('verified local cache bypasses remote source entirely', async () => { const parent = await tempRoot(); try { const f = await fixture(parent); let remote = 0; const local = { verify: async () => ({ exists: true, usable: true, verified: true, entry: { generation: f.manifest.image.generation } }), publish: async () => { throw new Error('not called'); } }; const acquisition = new ImageArtifactAcquisition({ directory: path.join(parent, 'acquire'), local, source: { manifest: async () => { remote += 1; }, fetch: async () => {} }, codec }); assert.equal((await acquisition.ensure({ identity: f.manifest.image.identity, generation: f.manifest.image.generation })).state, 'local'); assert.equal(remote, 0); } finally { await rm(parent, { recursive: true, force: true }); } });
test('missing local image reconstructs exact canonical bytes and admits through local port', async () => { const parent = await tempRoot(); try { const f = await fixture(parent); const source = sourceFor(f, { assertSize: (requested, actual) => assert.equal(requested, actual) }); const local = localPort(parent); const acquisition = new ImageArtifactAcquisition({ directory: path.join(parent, 'acquire'), local, source, codec }); let validated = false; const result = await acquisition.ensure({ identity: f.manifest.image.identity, generation: f.manifest.image.generation, validate: async ({ digest: sha }) => { validated = true; assert.equal(sha, f.manifest.image.sha256); } }); assert.equal(result.state, 'reconstructed'); assert.equal(validated, true); assert.equal(source.calls().fetches.length, f.manifest.chunks.length); assert.equal((await local.verify(f.manifest.image.identity)).verified, true); } finally { await rm(parent, { recursive: true, force: true }); } });
test('interrupted acquisition resumes from already verified chunks', async () => { const parent = await tempRoot(); try { const f = await fixture(parent, { chunkBytes: 4 }); const firstSource = sourceFor(f, { failFetch: (_name, count) => count === 2 }); const local = localPort(parent); const directory = path.join(parent, 'acquire'); await assert.rejects(() => new ImageArtifactAcquisition({ directory, local, source: firstSource, codec }).ensure({ identity: f.manifest.image.identity }), /injected/u); const secondSource = sourceFor(f); const result = await new ImageArtifactAcquisition({ directory, local, source: secondSource, codec }).ensure({ identity: f.manifest.image.identity }); assert.equal(result.reusedChunks, 1); assert.equal(secondSource.calls().fetches.includes(f.manifest.chunks[0].name), false); } finally { await rm(parent, { recursive: true, force: true }); } });
test('corrupt retained chunk is refetched while valid siblings are reused', async () => { const parent = await tempRoot(); try { const f = await fixture(parent, { chunkBytes: 4 }); const directory = path.join(parent, 'acquire'); const root = path.join(directory, 'chunks', f.manifest.encoding.sha256); await mkdir(root, { recursive: true }); await copyFile(path.join(f.bundle, f.manifest.chunks[0].name), path.join(root, f.manifest.chunks[0].name)); await writeFile(path.join(root, f.manifest.chunks[1].name), 'corrupt'); const source = sourceFor(f); const result = await new ImageArtifactAcquisition({ directory, local: localPort(parent), source, codec }).ensure({ identity: f.manifest.image.identity }); assert.equal(result.reusedChunks, 1); assert.equal(source.calls().fetches.includes(f.manifest.chunks[0].name), false); assert.equal(source.calls().fetches.includes(f.manifest.chunks[1].name), true); } finally { await rm(parent, { recursive: true, force: true }); } });
test('chunk, canonical, and subject substitutions fail closed', async () => { const parent = await tempRoot(); try { const f = await fixture(parent, { chunkBytes: 4 }); const corrupt = sourceFor(f, { chunk: (_name, bytes) => Buffer.concat([bytes, Buffer.from('x')]) }); await assert.rejects(() => new ImageArtifactAcquisition({ directory: path.join(parent, 'a1'), local: localPort(parent), source: corrupt, codec }).ensure({ identity: f.manifest.image.identity }), /chunk failed verification/u); const wrongManifestSource = sourceFor(f, { manifest: (value) => ({ ...value, image: { ...value.image, generation: 'other' } }) }); await assert.rejects(() => new ImageArtifactAcquisition({ directory: path.join(parent, 'a2'), local: localPort(parent), source: wrongManifestSource, codec }).ensure({ identity: f.manifest.image.identity, generation: f.manifest.image.generation }), /semantic image subject|another image/u); const badCodec = { ...codec, async decode({ destination }) { await writeFile(destination, 'wrong-canonical'); } }; await assert.rejects(() => new ImageArtifactAcquisition({ directory: path.join(parent, 'a3'), local: localPort(parent), source: sourceFor(f), codec: badCodec }).ensure({ identity: f.manifest.image.identity }), /canonical image failed verification/u); } finally { await rm(parent, { recursive: true, force: true }); } });
test('invalid existing local image must be quarantined before replacement', async () => { const parent = await tempRoot(); try { const f = await fixture(parent); const local = localPort(parent, { before: () => ({ exists: true, usable: false, verified: false, entry: { generation: f.manifest.image.generation } }) }); const result = await new ImageArtifactAcquisition({ directory: path.join(parent, 'acquire'), local, source: sourceFor(f), codec }).ensure({ identity: f.manifest.image.identity }); assert.equal(result.state, 'reconstructed'); assert.deepEqual(local.quarantined, [f.manifest.image.identity]); } finally { await rm(parent, { recursive: true, force: true }); } });
test('capacity blocker prevents any chunk transfer', async () => { const parent = await tempRoot(); try { const f = await fixture(parent); const source = sourceFor(f); const capacity = { ensure: async () => { throw new Error('insufficient image recovery storage'); } }; const acquisition = new ImageArtifactAcquisition({ directory: path.join(parent, 'acquire'), local: localPort(parent), source, codec, capacity }); await assert.rejects(() => acquisition.ensure({ identity: f.manifest.image.identity }), /insufficient/u); assert.deepEqual(source.calls().fetches, []); } finally { await rm(parent, { recursive: true, force: true }); } });
test('interrupted decode keeps verified chunks reusable on resume', async () => { const parent = await tempRoot(); try { const f = await fixture(parent, { chunkBytes: 4 }); const directory = path.join(parent, 'acquire'); const failingCodec = { ...codec, async decode({ destination }) { await writeFile(destination, 'partial'); throw new Error('decode interrupted'); } }; await assert.rejects(() => new ImageArtifactAcquisition({ directory, local: localPort(parent), source: sourceFor(f), codec: failingCodec }).ensure({ identity: f.manifest.image.identity }), /decode interrupted/u); const source = sourceFor(f); const result = await new ImageArtifactAcquisition({ directory, local: localPort(parent), source, codec }).ensure({ identity: f.manifest.image.identity }); assert.equal(result.reusedChunks, f.manifest.chunks.length); assert.deepEqual(source.calls().fetches, []); } finally { await rm(parent, { recursive: true, force: true }); } });
test('wrong encoding identity fails before transport', async () => { const parent = await tempRoot(); try { const f = await fixture(parent); const source = sourceFor(f); const acquisition = new ImageArtifactAcquisition({ directory: path.join(parent, 'acquire'), local: localPort(parent), source, codec: { ...codec, algorithm: 'other' } }); await assert.rejects(() => acquisition.ensure({ identity: f.manifest.image.identity }), /unsupported/u); assert.deepEqual(source.calls().fetches, []); } finally { await rm(parent, { recursive: true, force: true }); } });
