import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createRecoverableImageCache } from '../src/app/recoverable-image-cache.js';
const target = `img-${'1'.repeat(32)}`; const sibling = `img-${'2'.repeat(32)}`;
test('quarantine preserves exact bad bytes and protects unrelated cache subjects', async () => { const root = await mkdtemp(path.join(os.tmpdir(), 'db-cache-quarantine-')); try { const bad = path.join(root, 'bad.vhdx'); await writeFile(bad, 'corrupt-bytes'); const calls = []; const library = { verify: async () => ({}), publish: async () => ({}), observe: async () => ({ exists: true, location: bad, entry: { identity: target, digest: 'a'.repeat(64), size: 99 } }), list: async () => [{ identity: target }, { identity: sibling }], retire: async (identity) => { calls.push(['retire', identity]); }, collect: async ({ protectedIdentities }) => { calls.push(['collect', protectedIdentities]); return { removed: [target] }; } }; const cache = createRecoverableImageCache({ library, quarantineDirectory: path.join(root, 'quarantine'), id: () => 'fixed-1', now: () => '2026-08-22T08:00:00.000Z' }); const result = await cache.quarantine(target); assert.equal(result.retained, true); assert.equal(await readFile(path.join(root, 'quarantine', result.quarantine.file), 'utf8'), 'corrupt-bytes'); assert.deepEqual(calls, [['retire', target], ['collect', [sibling]]]); } finally { await rm(root, { recursive: true, force: true }); } });
test('missing bad bytes still clears only the exact catalog subject', async () => { const root = await mkdtemp(path.join(os.tmpdir(), 'db-cache-missing-')); try { const library = { verify: async () => ({}), publish: async () => ({}), observe: async () => ({ exists: false, location: path.join(root, 'missing'), entry: { identity: target, digest: 'a'.repeat(64), size: 99 } }), list: async () => [{ identity: target }, { identity: sibling }], retire: async () => {}, collect: async ({ protectedIdentities }) => { assert.deepEqual(protectedIdentities, [sibling]); return { removed: [target] }; } }; const result = await createRecoverableImageCache({ library, quarantineDirectory: path.join(root, 'quarantine') }).quarantine(target); assert.equal(result.changed, true); assert.equal(result.retained, false); } finally { await rm(root, { recursive: true, force: true }); } });
