import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { GitHubReleaseImageSource } from '../src/github/release-image-source.js';
function sha(bytes) { return createHash('sha256').update(bytes).digest('hex'); }

test('release source uses exact release id, pinned manifest digest, and bounded asset fetches', async () => { const manifestBytes = Buffer.from('{"protocol":"x"}\n'); const chunkBytes = Buffer.from('chunk'); const seen = []; const fetchImpl = async (url, options) => { seen.push({ url, options }); if (url.endsWith('/releases/42')) return new Response(JSON.stringify({ id: 42, assets: [{ id: 101, name: 'manifest.json', url: 'https://api.github.com/repos/iteathen/images/releases/assets/101', size: manifestBytes.length }, { id: 102, name: 'part-000', url: 'https://api.github.com/repos/iteathen/images/releases/assets/102', size: chunkBytes.length }] }), { status: 200, headers: { 'content-type': 'application/json' } }); if (url.endsWith('/releases/assets/101')) return new Response(manifestBytes, { status: 200, headers: { 'content-length': String(manifestBytes.length) } }); if (url.endsWith('/releases/assets/102')) return new Response(chunkBytes, { status: 200, headers: { 'content-length': String(chunkBytes.length) } }); throw new Error(`unexpected ${url}`); }; const source = new GitHubReleaseImageSource({ owner: 'iteathen', repository: 'images', releaseId: 42, manifestAsset: 'manifest.json', manifestDigest: sha(manifestBytes), token: () => 'secret-token', fetchImpl }); const supplied = await source.manifest(); assert.equal(supplied.digest, sha(manifestBytes)); const root = await mkdtemp(path.join(os.tmpdir(), 'db-release-source-')); try { const destination = path.join(root, 'part'); await source.fetch({ name: 'part-000', destination, size: chunkBytes.length }); assert.deepEqual(await readFile(destination), chunkBytes); assert.ok(seen[0].url.endsWith('/releases/42')); assert.equal(seen.some((entry) => /tags|branches/u.test(entry.url)), false); assert.equal(seen.every((entry) => entry.options.headers.Authorization === 'Bearer secret-token'), true); } finally { await rm(root, { recursive: true, force: true }); } });
test('release source rejects substituted manifest and size mismatches', async () => { const bytes = Buffer.from('{}\n'); const metadata = { id: 7, assets: [{ id: 1, name: 'manifest.json', url: 'https://api.github.com/repos/o/r/releases/assets/1', size: bytes.length }, { id: 2, name: 'part', url: 'https://api.github.com/repos/o/r/releases/assets/2', size: 5 }] }; const fetchImpl = async (url) => { if (url.endsWith('/releases/7')) return new Response(JSON.stringify(metadata), { status: 200 }); return new Response(bytes, { status: 200, headers: { 'content-length': String(bytes.length) } }); }; const source = new GitHubReleaseImageSource({ owner: 'o', repository: 'r', releaseId: 7, manifestAsset: 'manifest.json', manifestDigest: '0'.repeat(64), fetchImpl }); await assert.rejects(() => source.manifest(), /digest/u); const good = new GitHubReleaseImageSource({ owner: 'o', repository: 'r', releaseId: 7, manifestAsset: 'manifest.json', manifestDigest: sha(bytes), fetchImpl }); const root = await mkdtemp(path.join(os.tmpdir(), 'db-release-size-')); try { await assert.rejects(() => good.fetch({ name: 'part', destination: path.join(root, 'part'), size: 4 }), /metadata object size/u); } finally { await rm(root, { recursive: true, force: true }); } });
